### ISSUE TITLE
Strategy for Featuring Projects

### ISSUE THREAD

**Issue by cadecairos** [mozilla/api.webmaker.org#10]
How do we support all these requirements:
* should be able to filter by "release date", tag, locale, or version
* should support custom ordering
* should support pagination
* editable by "Admin" level accounts only

sounds like we should have a featured projects table in the database and expose an admin only API for adding, removing, ordering. 

And a public API for retrieving them, with optional sorting via fields specified above

**Comment by thisandagain** [comment]
I'm going to counter and say that a few of these requirements are not reflected in any of the designs (UX or UI) so we should remove them. That would just leave:
- Should support pagination
- Editable by "admin" level accounts only
- Should be sorted by `created_at` date
- Should be able to filter by `locale` (future release ... can punt)

#### API
```bash
GET /explore – Get featured projects w/ default limit & offset
GET /explore?locale=en_US – Get featured projects filtered by locale with default limit & offset
GET /explore?limit=20&offset=40 – Get featured projects w/ specified limit & offset

PUT /users/:user/projects/:project – Admins can set the `featured` flag to true
OR
POST /explore – Admins can post to the `explore` resource with a project id ... might be cleaner
```

#### Data Model
```js
[
    {
        // Array of projects from #6
    }
]
```

**Comment by xmatthewx** [comment]
Tags were noted in the pad as a potential future feature. Definitely not designed yet. Release date seems like a relic of appception. 

 - I believe @k88hudson included `version` to ensure that listed projects were compatible with current version of the app. 
 - Wondering if `updated_at` might be more useful than `created_at` for sorting content in locales where we cannot actively curate. A blog-like project might evolve long after it's created.

**Comment by thisandagain** [comment]
- Re: version. Makes sense. :+1: 
- Re: updated_at vs. created_at. My only worry with that is that users will be able to "bump" content up to the top of discover by making updates to their project if we use `updated_at`. Because the primary concern is to make that content feel fresh via curation, my suggestion is sorting by `created_at` will give us better control as a sorting mechanism.
