### ISSUE TITLE
Implement /skittles

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/api.webmaker.org#12]
Must produce candy with 100% colour coverage.

**Comment by cadecairos** [comment]
taste the rainbow. be the rainbow

**Comment by thisandagain** [comment]
WIP available here: https://github.com/cadecairos/api.webmaker.org/tree/skittles

**Comment by secretrobotron** [comment]
:+1:

* 1.0.0? https://github.com/cadecairos/api.webmaker.org/blob/skittles/services/api/index.js#L18
* Is there a reason `services/api/adapters/plugins.js` isn't `services/api/adapters/index.js` or something?
* <3 https://github.com/cadecairos/api.webmaker.org/blob/skittles/services/api/handlers/skittles.js
* <3 how simple this looks https://github.com/cadecairos/api.webmaker.org/blob/skittles/services/api/routes/authenticated.js
  * Would love to see a more complicated example (with `pre` defined, maybe)
* Yay for preparedness :) https://github.com/cadecairos/api.webmaker.org/blob/skittles/lib/csp.js
  * where does it get used?
* lol https://github.com/cadecairos/api.webmaker.org/blob/skittles/server.js#L20
  * should probably just bail if not specified by env
* cors?

https://www.youtube.com/watch?v=DUx6VWmmcck

**Comment by cadecairos** [comment]
> 1.0.0? https://github.com/cadecairos/api.webmaker.org/blob/skittles/services/api/index.js#L18

doesn't really matter what's there, it's just a requirement of the plugin API

> Is there a reason services/api/adapters/plugins.js isn't services/api/adapters/index.js or something?

I plan on adding in metrics, logging, possibly other adapters in that folder.

> Would love to see a more complicated example (with pre defined, maybe)

I'll have to experiment with pre configuration and see whats nice and not. will consult with @jbuck 

> where does it get used?

It'll get used when we migrate id over as a service plugin, as it'll bring in some front end stuff. It also is being used on the documentation routes as a nice side-effect.

> should probably just bail if not specified by env

can totally bail.

> cors?

can add as an adapter

**Comment by cadecairos** [comment]
I'll be running my latest code at  http://skittles-api.herokuapp.com/docs
