### ISSUE TITLE
What do Page Elements look like?

### ISSUE THREAD

**Issue by cadecairos** [mozilla/api.webmaker.org#13]
Lets define what the elements of pages look like, how they're stored, and how they relate to pages.

**Comment by xmatthewx** [comment]
Here's a list of elements and attributes. Ignore things in gray:  https://docs.google.com/presentation/d/1ihVXe53q6U7YLKiYURKXedE5TzOW7x7iwCNeJBY4dpE/edit#slide=id.ga9196a78b_043

**Comment by xmatthewx** [comment]
cc @flukeout

**Comment by flukeout** [comment]
For reference, here's the JSON I used to store a project in the Desk 8 prototype:
http://flukeout.com/examples/desk8/

This approach worked OK, I used a unique ID for each element, but only referenced tiles by their "x,y" coordinates. I'd probably switch tiles to have a unique ID as well ultimately.

```
{
"name":"My Project",
"background":"#648924",
"tiles":{
  "10:10": {
    "x":10,
    "y":10,
    "color":"#648924",
    "animation":"none",
    "elements":{
      "3194e236-04d7-1c9e-8139-245d3183224b": {
        "height":160,
        "type":"image",
        "width":160,
        "x":61,
        "y":38,
      "animation":"jiggle",
      "css":{
        "background-image":"kitten.png",
        "border-radius":100
      }
    },
    "4bd9f6ad-6133-f9c7-d83f-69c9a5dc89a2": {
      "height":60,
      "type":"text",
      "width":260,
      "x":100,
      "y":280,
      "animation":"pulse",
      "text":"Hello!",
      "css":{
        "font-size":"34",
        "text-align":"center"
      }
    }
  }},
  "10:11":{
    "x":10,
    "y":11,
    "color":"#24893e",
    "animation":"none",
    "elements":{
      "23968c19-1288-4cfb-baf3-db97d8500ec9":{
        "type":"text",
        "x":86,
        "y":255,
        "height":111,
        "width":246,
        "animation":"none",
        "text":"I am text!",
      "css":{
        "font-size":"48",
        "text-align":"right"
        }
      }
    }
  },
  "9:10":{
    "x":9,"y":10,
    "color":"#244889",
    "animation":"none",
    "elements":{}
  },
  "10:9":{
    "x":10,
    "y":9,
    "color":"#FFFFFF",
    "animation":"none",
    "elements":{}
  },
  "11:10":{
    "x":11,
    "y":10,
    "color":"#648924",
    "animation":"none",
    "elements":{
      "54c01e30-2ff1-87dc-95b8-ca70c550e011":{
        "type":"tilebutton",
        "x":41,
        "y":47,
        "goto":"10:11",
        "height":90,
        "width":200,
        "label":"Tap me!",
        "animation":"pulse",
        "css":{},
        "config":{
          "goto":"9:10"
          }
        }
      }
    }
  }
}
```

**Comment by cadecairos** [comment]
After consulting with Pomax, and based on the blobs above, I think this might best serve our needs for elements, especially if we plan on adding/deprecating props/transforms/styles

```sql
CREATE TABLE element (
  id NOT NULL serial,
  type NOT NULL varchar(32),
  properties json,
  transforms json,
  styles json
);
```

Thoughts? @thisandagain @Pomax @jbuck @gvn

**Comment by cadecairos** [comment]
more info:

properties will store things like "string" for the text element and "destination" for the button link

transforms will describe positional, rotational, and scaling information about an element

styles will describe the CSS attributes to be applied to the element.

**Comment by Pomax** [comment]
I'd say unrestrict the varchar, PG is good at figuring out how much space it needs for a plain varchar already, no need to limit ourselves to 32 characters (eye on the future etc.).

The properties, transforms and styles would map to the "element's attributes and content" (i.e. link url and text, or image src and alt, etc), the position identity (x/y/z, w/h, scale, rotation), and the CSS, respectively.

One thing we probably need to figure out is: who encodes the element ordering (e.g. text, image, text vs. image text text). Should elements "know" which position they're in on a page, or should pages track this per element they use?

**Comment by cadecairos** [comment]
I think we might want to indicate the elements "page index" rather than try to track positions of elements in the pages table

**Comment by thisandagain** [comment]
Should `type` just be an `enum` (image, text, link)?

**Comment by cadecairos** [comment]
I proposed that, and while it would be nice, it would require a DB migration every time we add/remove an element type. We'd have to be cool with doing that.

**Comment by thisandagain** [comment]
I'm pretty cool with that as we only have these three datatypes in the roadmap out to next year.

**Comment by cadecairos** [comment]
![](http://media.giphy.com/media/VLoN2iW8ii3wA/giphy.gif)

**Comment by xmatthewx** [comment]
The desktop code element is TBD, but if its container is a positionable element (rather than the page itself), would that be included here?

**Comment by thisandagain** [comment]
Good catch @xmatthewx .

```sql
CREATE TYPE element AS ENUM ('image', 'text', 'link', 'code');
```

**Comment by davidascher** [comment]
Probably worth scheduling a db migration just for fun so we know that we
know how to do that in advance anyway.

**Comment by Pomax** [comment]
I don't see any benefit to an enum right now for the `type`. It's the same kind of restriction as varchar with a number: keep it a string and we can easily play around with types while we work our way to release. This also allows for future "custom elements". (bottom line: enums pretend we know what we're doing already. we don't)

**Comment by thisandagain** [comment]
Ok. Point taken ... `varchar` it is.

**Comment by thisandagain** [comment]
#### API
```bash
GET /users/:user/projects/:project/pages/:page/elements
POST /users/:user/projects/:project/pages/:page/elements

GET /users/:user/projects/:project/pages/:page/elements/:element
PUT /users/:user/projects/:project/pages/:page/elements/:element
DEL /users/:user/projects/:project/pages/:page/elements/:element
```

#### Data Model
```js
{
    "id": 1234,
    "type": "image",
    "properties": {},
    "transforms": {},
    "styles": {}
}
```

#### SQL
```sql
CREATE TABLE element (
  id serial PRIMARY KEY,
  type varchar NOT NULL,
  properties json,
  transforms json,
  styles json
);
```
