### ISSUE TITLE
prerequisites.js isOwner does a strict compare, but inputs are not strictly the same

### ISSUE THREAD

**Issue by Pomax** [mozilla/api.webmaker.org#130]
we check ownership in https://github.com/mozilla/api.webmaker.org/blob/develop/services/api/lib/prerequisites.js#L3-6, but a console log of the inputs to that function reveals that the `request.auth.credentials.id` value that we use for token comparison is a numeric type, where the other two inputs are string types, and so the `isOwner` check fails on input like `1, '1', '1'` because of strict comparison (using `===`).

We could use `==` comparison here, or we could force string type with something like:
```
function isOwner(tokenId, userId, projectId) {
  tokenId = '' + tokenId;
  userId = '' + userId;
  projectId = '' + projectId;
  return (tokenId === userId && userId === projectId);
}
```

Do we have a preference? (I'd imagine `==` might throw up linting errors)

**Comment by cadecairos** [comment]
yeah, lets coerce to string with `'' + foo`
