### ISSUE TITLE
Load test /discover/{language}

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/api.webmaker.org#139]
We just added a new route today to filter the discover gallery by language. Would be useful to see how it impacts server performance.

e.g.
```
https://api.webmaker.org/discover/en-CA
https://api.webmaker.org/discover/fr-CA
https://api.webmaker.org/discover/bn-BD
```

**Comment by secretrobotron** [comment]
cc @cadecairos

**Comment by secretrobotron** [comment]
@cadecairos is that endpoint automagically cached?

**Comment by cadecairos** [comment]
We did test this, and it is cached, and performed quite well! closing this.

![screenshot from 2015-08-07 14-49-40](https://cloud.githubusercontent.com/assets/438003/9143315/90b628d6-3d13-11e5-8070-b9fcbf519e0d.png)

**Comment by thisandagain** [comment]
:+1:
