### ISSUE TITLE
Generate missing thumbnails

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/api.webmaker.org#172]
Projects created since snippet launch are missing thumbnails.

cc @cadecairos @ashleygwilliams

**Comment by xmatthewx** [comment]
related: https://github.com/mozilla/api.webmaker.org/pull/94

**Comment by cadecairos** [comment]
I thought doing this would be fairly straight forward (and it kinda is)... Here's a breakdown of the steps

1. Select min(page.id), and its associated project_id and user_id for all projects that have no thumbnail
2. for Each set of ids, generate a thumbnail URL using thumbnail service and save row to database
3. bust the projects.findOne and projects.findUsersProjects server caches for each set of data

Which is going to be one heck of a script.

Is it worth the effort?

**Comment by xmatthewx** [comment]
@secretrobotron - We had a snafu with thumbnails. Trying to weight the cost & benefit of generating them for existing projects. It will certainly impact users who return to the app after playing around ... and make it easier for you to browse new projects to feature. 

@cadecairos - how much time would you estimate?

**Comment by cadecairos** [comment]
half a days worth of work to write and test the script

**Comment by secretrobotron** [comment]
:+1: 

@cadecairos *lots* of the projects are empty. detecting those and skipping over them will be useful, i bet.

**Comment by xmatthewx** [comment]
Thanks for the speedy work on this. Are we throttling the script? Should we, to avoid impact on active users?

**Comment by cadecairos** [comment]
It shouldn't interfere with any active users, afaict. I'm monitoring prod stats just in case

**Comment by cadecairos** [comment]
also, it's throttled to only update one project at a time.

**Comment by xmatthewx** [comment]
Cool cool :relieved:

**Comment by cadecairos** [comment]
We're all fixed up!

```
~ $ node scripts/regenerate_thumbnails.js "projects.thumbnail = '{}'"
Found 0 rows to update
Thumbnail queue empty. Nice job!
```

**Comment by xmatthewx** [comment]
:dart:   :clap: :cake:
