### ISSUE TITLE
Figure out where to store sensitive data and how we'll access it

### ISSUE THREAD

**Issue by cadecairos** [mozilla/api.webmaker.org#18]
We want api.wmo to be secure, but we also want it to be easy to develop for.

With those goals in mind, we need to identify how/where we store passwords, emails, and Oauth data (tokens, clients, authorizations) and how api.wmo will access that data in as securely a way as possible, without compromising the developer experience.

"You're crazy, you can't have both of those things!"

 I disagree.

We should have a meeting and argue about this: @jbuck @simonwex @thisandagain @xmatthewx @Pomax @gvn 

\+ anyone else who might be interested

**Comment by cadecairos** [comment]
+ @secretrobotron

**Comment by secretrobotron** [comment]
+ @adamlofting

**Comment by secretrobotron** [comment]
@cadecairos do you already have a sketch of a plan?

**Comment by cadecairos** [comment]
![](https://docs.google.com/a/mozillafoundation.org/uc?id=0BzTHM7WIfEtubER0TlZJNTNqM3c)

Concept

**Comment by cadecairos** [comment]
An important detail about API.wmo and the user/oauth services is that we can write them as hapi plugins.

They can be stored in the same repo and deployed on their own in staging/prod or spun up all at once in a development environment. We could also maintain them as separate repos which are included as devDependencies on API / ID and are started up for local dev, but can be independently configured and deployed for staging/production environments

It sounds like a lot of work, but provides separation of sensitive/non-sensitive data, and provides an increase in difficulty pwning the user/oauth databases

**Comment by thisandagain** [comment]
Can you outline what kinds of data would be stored in the User DB vs. the Webmaker DB?

**Comment by cadecairos** [comment]
### User DB
* uid
* email
* username
* account preferences

### Password DB
* password hash
* salt
* user uid

### Webmaker DB
* project, page, & element data (all stored with user uid)
* future webmaker application data tables

**Comment by cadecairos** [comment]
@jbuck said it best. "this stuff looks nice. but, is it *necessary*" which is a question we should ask someone with sufficient knowledge to answer yes or no.

**Comment by thisandagain** [comment]
:+1: yup ... that is right on. In particular I'm not sure about the split between the Password and User DBs, but we should consult our friendly neighbor infosec experts. 

@simonwex any ideas for how to resolve this / who to talk to?

**Comment by secretrobotron** [comment]
Silly question: I don't actually see Password DB in the diagram, but I **do** see OAuth DB. Is that what y'all meant?

**Comment by cadecairos** [comment]
Hmm yeah, i mixed that up. Mash together user and password, add a db for handling oauth data.

**Comment by simonwex** [comment]
Separating PII + passwords from other data is important from an operations perspective. That is, we have a separate AWS account which has very limited access. We should work towards running entire projects that deal with PII under that account. PII includes email, so I think the delineation isn't quite right above.

Baddies obtaining a list of all webmaker email addresses would be as bad, if not worse than Webmaker accounts being compromised.

**Comment by thisandagain** [comment]
:+1: thanks @simonwex 

So, just to reiterate:

#### Webmaker DB (mofo)
- Public user content (projects, pages, elements)
- Future public content such as comments and favorites 

#### User DB (mofo-secure)
- uid
- email
- username
- account preferences
- password hash
- salt

#### OAuth DB (mofo-secure)
- oauth tokens

If this is correct, my only major question is why would we separate the OAuth DB from the User DB? Seems arbitrary.

**Comment by thisandagain** [comment]
Also ... it's a little odd / seems insecure to store the salt in the DB where you have your hashed passwords.

**Comment by simonwex** [comment]
Agreed on the separation of auth/user db. @cadecairos, @jbuck this can be accomplished by dbuser permissions, no?

As for the salts, it's about being unique to that password not a secret. A unique salt combined with a global secret (stored in env of application server) makes the use of tools like rainbow tables infeasible AFAIK.

**Comment by thisandagain** [comment]
Got it. Thanks for the clarification on salts ... I originally thought salt = global secret when I looked at the listing. :+1:

**Comment by Pomax** [comment]
if user's have a uid, do we need a separate salt value? The point of salting is to prevent a rainbow attack against the entire user table by salting per user, simply taking the uid as  the salting value seems just as effective in terms of creating a uniquely salted hash?

**Comment by simonwex** [comment]
It does *seem* right, but something about the small bit-count and predictability of ids-as-hashes makes my spidey senses tingle.

![image](https://cloud.githubusercontent.com/assets/25260/7419168/31fbf75a-ef28-11e4-976b-5fa889c78ecc.png)

**Comment by Pomax** [comment]
Technically it doesn't particularly matter since the point of the salt is a low number of bits, since the hashing algorithm should guarantee *wildly* different hashes if even a single bit changes on the input. The only thing that's relevant for salting is that it needs to simply "be different" on a per-user basis, so that a rainbow attack that works for one user simply won't work for any other user. Even if you can predict what the salt is going to be, you'd still need to generate unique rainbow tables for each user. 

Salting doesn't make things "more secure" on a per user basis (you can still bust it, given enough time) it just makes things more secure for the collection as a whole.

(I'm assuming that we're not using "an autoincrementing int" for ids, here, btw, but a more useful 32 bit uuid or the like)
