### ISSUE TITLE
incorrect fonts on Webmaker thumbnails

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/api.webmaker.org#180]
Thumbnail service stopped using correct fonts at some point. 

Anr example: https://beta.webmaker.org/?user=421495&project=22424#/project?user=421495&project=22424

project:
![image](https://cloud.githubusercontent.com/assets/53411/10136862/bb1fc5bc-65c4-11e5-9c65-7df6d879d679.png)

thumb:
![image](https://cloud.githubusercontent.com/assets/53411/10136878/cd5f2d08-65c4-11e5-9018-f38dd3f7e86c.png)

**Comment by jbuck** [comment]
We should figure out which project is newer and/or older, and provide that info to the provider

**Comment by xmatthewx** [comment]
Either it's fixed, or it was a temporary problem. I had projects, both old and new, with the wrong fonts in thumbs. I regenerated them by editing the page, and now they are ok. 

Maybe it's an intermittent problem if fonts load slowly on their service?
