### ISSUE TITLE
Add description to projects

### ISSUE THREAD

**Issue by cadecairos** [mozilla/api.webmaker.org#182]
part one of adding tags to projects.

Details:
`description` will be a `character varying(100)` type. It will need to be added as a param on project creation (optional, default to ''). Update code will need to be modified, and project formatting utilities updated.

This is all basically done in my hashtags branch, which I'll pull in here, sans the tag features and code.

cc/ mozilla/webmaker-core#727

**Comment by jbuck** [comment]
I'd recommend the TEXT type instead.
