### ISSUE TITLE
Implement Projects Endpoint

### ISSUE THREAD

**Issue by cadecairos** [mozilla/api.webmaker.org#19]
Details in #6

* [ ] SQL statements
* [ ] Implement routes
* [ ] tests

**Comment by xmatthewx** [comment]
Do we require unique titles for projects per user?

**Comment by xmatthewx** [comment]
@LauraReynal was asking about URLs for sharing. Wondering which is nicer for people:
 -  http://webmaker.org/cade/summer_2015
 - http://webmaker.org/cade/[project-ID]/summer_2015
