### ISSUE TITLE
Remove description from remixed project

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/api.webmaker.org#191]
Descriptions shouldn't be included in a remix. Browsing by hashtag will be cluttered by many remixes that don't have meaningful changes, making it hard to find the good stuff. 

@cadecairos - if this just requires removing [this one line](https://github.com/mozilla/api.webmaker.org/blob/bb88329180c8446747c29742d5e708edd6dbaa54/services/api/lib/queries.js#L58), I can submit the PR.

**Comment by cadecairos** [comment]
It's going to take a little more that that: 

https://github.com/mozilla/api.webmaker.org/blob/bb88329180c8446747c29742d5e708edd6dbaa54/services/api/lib/postgre.js#L215 - that will need to become and empty string

**Comment by xmatthewx** [comment]
Ok. I'll let you figure out the best way to handle that.

**Comment by xmatthewx** [comment]
This is done, right? On production?

**Comment by xmatthewx** [comment]
@cadecairos - let's land this on Master.
