### ISSUE TITLE
Regenerate Thumbs

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/api.webmaker.org#196]
Service went down about two weeks ago (#194). Run script to generate missing thumbs.

**Comment by xmatthewx** [comment]
We could run script on projects starting at id = 50000. That might miss a few projects that were edited, but will catch on the newly made ones lacking any thumb.

**Comment by xmatthewx** [comment]
I don't think anything has changed that would impact the script: https://github.com/mozilla/api.webmaker.org/blob/develop/scripts/regenerate_thumbnails.js

**Comment by cadecairos** [comment]
running this now, regenerating thumbs for ~6000 projects

**Comment by xmatthewx** [comment]
:checkered_flag:  :runner: :dash:

**Comment by xmatthewx** [comment]
done!
