### ISSUE TITLE
id.webmaker.org integration

### ISSUE THREAD

**Issue by cadecairos** [mozilla/api.webmaker.org#26]
* [x] connect to id.webmaker.org for token verification [1]
* [x] remove auto incrementing userid field,. link to id.wmo userid
* [x] Tests

~~[1] Blocked, mozilla/id.webmaker.org#296~~

**Comment by cadecairos** [comment]
We're not storing Tokens here, evolving ticket....

**Comment by cadecairos** [comment]
for some reason github won't let me upload a picture, so, 

![](https://docs.google.com/a/mozillafoundation.org/uc?id=0BzTHM7WIfEtuX19uZzlOVWRrWTQ&export=download)

**Comment by cadecairos** [comment]
@simonwex: See the above comment

**Comment by cadecairos** [comment]
@simonwex original draw.io file https://www.dropbox.com/s/z6abwhi4s6fax26/Webmaker-new-user.html?dl=0

I'm not sure if that makes it editable for others on draw.io...

**Comment by simonwex** [comment]
@cade, not editable but this is great work. Where will this live long-term?

**Comment by simonwex** [comment]
&nbsp;&nbsp;&nbsp;&nbsp; :speech_balloon: - May I suggest in the project README?
:sunglasses:

**Comment by cadecairos** [comment]
I found a way to edit it, but it's totally not obvious. 

filed #58

**Comment by cadecairos** [comment]
Fixed by #54
