### ISSUE TITLE
Select a framework

### ISSUE THREAD

**Issue by cadecairos** [mozilla/api.webmaker.org#3]
Lets officially choose a framework for this app. 

Candidites are: Express, Hapi, Koa, Restify, Sails

I'm voting for Hapi, based on my experiences using it for id.wmo, it's highly testable, and quite suitable for API's VS Express

**Comment by cadecairos** [comment]
cc/ @simonwex @jbuck @k88hudson @Pomax @alicoding

**Comment by thisandagain** [comment]
:+1: on Hapi as my preference. Second choice would be restify.

**Comment by thisandagain** [comment]
HAPI is go.
