### ISSUE TITLE
Select a Database

### ISSUE THREAD

**Issue by cadecairos** [mozilla/api.webmaker.org#4]
What should we use to store our data?

NoSQL? MySQL? Postgre? 

Will we use an ORM like sequelize?

How will we handle migrations?

**Comment by cadecairos** [comment]
cc/ @simonwex  @jbuck

**Comment by thisandagain** [comment]
Given the nature of the data (structured, highly relational), it seems like good 'ol boring PG or MySQL is the way to go. I don't have a strong opinion in terms of which flavor we choose, though I would prefer we avoid an ORM and provide migrations with each version change of the API.

**Comment by simonwex** [comment]
:+1: for PG or MySQL.

Unfortunately, there is still no state-of-the-art for ORMs in node and I
don't want us to build one.

Do have a look around for migration libraries, though -- I think there are
a couple decent looking ones.

**Comment by thisandagain** [comment]
I've had decent luck with https://github.com/db-migrate/node-db-migrate in the past.

**Comment by thisandagain** [comment]
Do we need to talk about caching layer / datastore now as well @jbuck @simonwex ?

**Comment by simonwex** [comment]
@thisandagain I think we can defer that until we start to see an uptick in volume. Do we have any load testing issues filed? It would be nice to know when to plan for.

**Comment by thisandagain** [comment]
@simonwex Most likely not a problem though I'll look at the marketing / snippet schedule and advise. Re: load-testing – we don't have any issues filed yet, but we should add at least one round to the roadmap after we walk through the marketing strategy next week and have a better idea of what to expect at launch. 

Another thought is we should define a baseline for performance (e.g. "<= 40ms average response time per 5 minute sample") for the application. Do we have any standards already established here?

/cc @jbuck @cadecairos

**Comment by thisandagain** [comment]
PG is go pending @jbuck verifying that read replication and multi-AZ fail-over is available from RDS.

**Comment by jbuck** [comment]
Yep, Postgres supports read replicas and multi-AZ fail-over http://aws.amazon.com/rds/postgresql/

**Comment by thisandagain** [comment]
:boom:
