### ISSUE TITLE
Duplicate coordinates not allowed for deleted pages

### ISSUE THREAD

**Issue by k88hudson** [mozilla/api.webmaker.org#43]
STR:

1. Delete a page with coordinates 0, -1
2. Create a new page with coordinates 0, -1

Expected: Page is created
Actual: 400 error returned, duplicate coordinates not allowed.

**Comment by thisandagain** [comment]
This *should* be as easy as updating the `CHECK` constraint:
http://www.postgresql.org/docs/current/interactive/ddl-constraints.html#DDL-CONSTRAINTS-CHECK-CONSTRAINTS

**Comment by k88hudson** [comment]
@thisandagain k ill give it a go

**Comment by k88hudson** [comment]
@thisandagain hm, unfortunately since we're using UNIQUE this might be a bit tricky, two null values are not considered equal http://www.postgresql.org/docs/current/interactive/ddl-constraints.html#DDL-CONSTRAINTS-UNIQUE-CONSTRAINTS
