### ISSUE TITLE
What will Projects and Pages look like

### ISSUE THREAD

**Issue by cadecairos** [mozilla/api.webmaker.org#5]
Lets figure out what these are going to look like, at least for Alpha

**Comment by cadecairos** [comment]
@Pomax I was told you might have a better idea about storing theses things, can you add some information here?

cc/ @jbuck @simonwex

**Comment by thisandagain** [comment]
:+1: I'd love to see some options for representation here. @gvn and @Pomax can you drop an example of the JS objects that you are rendering in the current build?

**Comment by gvn** [comment]
Right now my "projects" are just 2 dimensional arrays with either `null` or `"empty"` as values.

**Comment by thisandagain** [comment]
Interesting ... so that seems to suggest that the grid is of a defined dimension (3x3 in this example), correct? Any thoughts on using a Cartesian co-ordinate system?

```js
[
    {
        id: 1,
        x: 0,
        y: 0,
        // some other page stuff goes here
    },
    {
        id: 2,
        x: 1,
        y: 0,
        // some other page stuff goes here
    }
]
```

**Comment by gvn** [comment]
Hmm...that'd require significant refactoring, but it's possible. Is there a benefit?

It's not a fixed grid, FWIW. It expands as needed...

**Comment by thisandagain** [comment]
The major benefit I see is in persistence and thrift. Let's use a hypothetical example based on the interface spec – let's say a user takes a project with three tiles and moves the tile in `0,0` to position `10,10`:

#### 2-dimensional Array
```js
[
    [{},null,null],
    [null,{},null],
    [{},null,null]
]
```

```js
[
    [null,null,null,null,null,null,null,null,null,null],
    [null,{},null,null,null,null,null,null,null,null],
    [{},null,null,null,null,null,null,null,null,null],
    [null,null,null,null,null,null,null,null,null,null],
    [null,null,null,null,null,null,null,null,null,null],
    [null,null,null,null,null,null,null,null,null,null],
    [null,null,null,null,null,null,null,null,null,null],
    [null,null,null,null,null,null,null,null,null,null],
    [null,null,null,null,null,null,null,null,null,null],
    [null,null,null,null,null,null,null,null,null,{}],
]
```
#### Cartesian
```js
[
    { id: 1, x: 0, y: 0 },
    { id: 2, x: 1, y: 1 },
    { id: 3, x: 0, y: 2 }
]
```

```js
[
    { id: 1, x: 10, y: 10 },
    { id: 2, x: 1, y: 1 },
    { id: 3, x: 0, y: 2 }
]
```

---

If we are representing pages in a relational DB, this means we have only one resource (one row in this case) that needs to be updated. The major disadvantage here is that we need to enforce a unique constraint on the x/y tuple on a per-project basis ... but that seems more manageable than needing to persist 2-dimensional arrays of n-length. Thoughts?

@gvn @Pomax @cadecairos @jbuck @simonwex

**Comment by gvn** [comment]
It should be easy enough for me to do a translation to your schema for persistence. I'll probably still use the 2D array in the UI code (at least for the time being).

PS: I didn't think someone could actually add a tile anywhere except adjacent to a neighboring tile FWIW.

**Comment by thisandagain** [comment]
Cool... that makes total sense. They can only create new tiles adjacent to existing tiles but in the prototypes you can drag a tile anywhere.

**Comment by simonwex** [comment]
:+1: to implementing a coordinate-based system. In my mind this provides a few advantages over relying on relative indexing in a single large array. The biggest one being that we could deal with parts of projects. -- If we store and transfer a project as a single array, if parts of the project are omitted, the context of any one tile is lost.

Why would partial projects be useful?
* We will likely want to affect individual tiles on CRUD operations to be more conservative on bandwidth usage.
 * one could imagine POST /tile/2/3 to create a new tile
* Large projects would likely benefit from lazy loading, especially on mobile

I'd suggest we allow for negative indexes out of the gate and have the default first tile 0,0. This will save us from complicated index shifting operations.

**Comment by simonwex** [comment]
Having easily-accessible x,y coordinates makes math for transitions much easier, too.

**Comment by gvn** [comment]
Determining the width/height of the grid with Cartesian is more difficult though unless we add that to the schema (slightly weird since it can be derived from the existing data and is a "sugar" value that can get out of sync).

**Comment by simonwex** [comment]
I would recommend we don't store a calculated value there. We can store `project_id, x, y` in the db as columns. `SELECT min(x), max(x), min(y), max(y) from tiles;` would do the trick for setting up the initial grid. Focussing on 0,0 being the centre might get rid of that need, though.

**Comment by gvn** [comment]
Do you mean `page_id` instead of `project_id`?

**Comment by simonwex** [comment]
I think I mean project. Riddle me this, is tile synonymous with page? If so, the x, y is what makes a page/tile unique within a project.

**Comment by gvn** [comment]
Yeah, page == tile. A project would contain many pages/tiles.

**Comment by thisandagain** [comment]
Cool. Here is another sketch based on this conversation and #6 :

#### API
```bash
POST /users/:user/projects – Create a new project
GET /users/:user/projects/:project – Get an existing project by ID
PUT /users/:user/projects/:project – Update an existing project by ID (auth, owner)
DEL /users/:user/projects/:project – Delete an existing project by ID (auth, owner)
```
```bash
POST /users/:user/projects/:project/pages – Create a new page
GET /users/:user/projects/:project/pages/:page – Get an existing page by ID
PUT /users/:user/projects/:project/pages/:page – Update an existing page by ID (auth, owner)
DEL /users/:user/projects/:project/pages/:page – Delete an existing page by ID (auth, owner)
```

#### Data Model
```js
{
    "id": 1,
    "title": "Yam Fries 4000",
    "featured": true,
    "author": {
        "url": "billmurray",
        "username": "Bill Murray",
        "locale": "en_US",
        "permissions": {
            "staff": false,
            "moderator": false
        },
        "avatar": {
            // @todo
        }
    },
    "cover": {
        // @todo
    }
}
```
```js
[
    {
        "id": 1,
        "x": 0,
        "y": 0,
        "elements": [
            // @todo
        ]
    },
    // etc ...
]
```

#### SQL
```sql
CREATE TABLE projects (
    id bigserial PRIMARY KEY,
    created_at timestamp DEFAULT current_timestamp,
    updated_at timestamp DEFAULT current_timestamp,
    deleted_at timestamp,
    title varchar(64) NOT NULL,
    user_id bigint NOT NULL
);
```
```sql
CREATE TABLE pages (
    id bigserial PRIMARY KEY,
    created_at timestamp DEFAULT current_timestamp,
    updated_at timestamp DEFAULT current_timestamp,
    deleted_at timestamp,
    x integer DEFAULT 0 NOT NULL,
    y integer DEFAULT 0 NOT NULL,
    project_id bigint NOT NULL,
    UNIQUE(project_id, x, y)
);
```

Thoughts? @cadecairos @gvn @Pomax @simonwex @jbuck

**Comment by Pomax** [comment]
I'd extend the projects table with a "description" field; just having a title for a project feels too sparse

**Comment by thisandagain** [comment]
Good questions!

- Re: description. Do we have a spec for that? I don't think we have description in the UX spec, but this should absolutely evolve if I missed it! (cc @xmatthewx )
- Re: username. Nope ... old habit. Great catch. I'll remove that from #9

**Comment by xmatthewx** [comment]
@vazquez will complete the "settings" view this week. I added a note to include a description, though I think they should be de-emphasized and not required. They benefit us always, the user sometimes. Descriptions add friction to sharing smaller, quick, fun projects.

**Comment by cadecairos** [comment]
Should I file another bug for discussions about representing page elements in the database?

**Comment by thisandagain** [comment]
@cadecairos :+1: Yup ... sounds good. The page / element / attribute relationship is one of the larger  open questions.

**Comment by cadecairos** [comment]
TIL that postgre has a native Point datatype (x, y) which might prove handy for pages?

http://www.postgresql.org/docs/9.4/static/datatype-geometric.html#AEN6730

**Comment by thisandagain** [comment]
Woah... I didn't know about these geometic datatypes! However, it looks like points in Postgres are a pair of floats whereas we just need two signed 16-bit integers.

**Comment by davidascher** [comment]
I'd avoid postgres-specific datatypes unless there's a really good reason
to use them.  Would make migration harder.

**Comment by Pomax** [comment]
though as remark on migration difficulties: MariaDB has a json datatype (and supports dynamic columns per record, which is basically json-as-columns), so JSON these days is relatively easy to migrate.

**Comment by thisandagain** [comment]
Yup. :+1: @Pomax I'm cool with making an exception for the `json` datatype. I agree that the really crazy geolocation stuff in PG along with a few other examples (these geometry datatypes for example) are a good idea to avoid.

**Comment by simonwex** [comment]
Make sure whatever provider we use has a recent-enough version of postgress to allow for indexing of json data.
