### ISSUE TITLE
Create a page at 0,0 when a project is created

### ISSUE THREAD

**Issue by k88hudson** [mozilla/api.webmaker.org#53]
There is never really a case when we want to have an empty project. Right now I am handling this second POST request on the client, but should we maybe add this functionality to the API and return an error/reverse the transaction if either fails?

**Comment by k88hudson** [comment]
cc @cadecairos @thisandagain

**Comment by thisandagain** [comment]
I agree. :+1:

**Comment by cadecairos** [comment]
I'll have to think about how to add transactions into the request lifecycle

**Comment by cadecairos** [comment]
This looks handy: https://github.com/iceddev/pg-transact

**Comment by thisandagain** [comment]
Resolved in #61

**Comment by cadecairos** [comment]
Actually, this is related to #59
