### ISSUE TITLE
Provide a Header based approach to API versioning

### ISSUE THREAD

**Issue by cadecairos** [mozilla/api.webmaker.org#55]
If we make a breaking change to the API, we need to provide a way for out of date apps to continue functioning.

@thisandagain proposed using a Header to specify the required API version.

I'm not entirely sure what this will look like in terms of route prerequisites, handlers, param validation, and testing.

**Comment by thisandagain** [comment]
For reference, check out the way Restify handles this (see: "Versioned Routes") http://mcavage.me/node-restify/#routing

**Comment by cadecairos** [comment]
This hapi plugin looks like exactly what we want: 

https://github.com/corintho/hapi-version

Unfortunately, it means we need to always maintain compatibility in out route prerequisite functions and server methods (db func)
