### ISSUE TITLE
Design Project API

### ISSUE THREAD

**Issue by cadecairos** [mozilla/api.webmaker.org#6]
* Create a project
  * POST /projects
* Update project
  * PATCH /projects/{id}
* Delete a project
  * DELETE /projects/{id}
* Get project data
  * GET /projects/{id}
* Get remixes of a project
  * GET /projects/{id}/remixes
* Create a remix of a project
  * POST /projects/{id}/remixes

**Comment by xmatthewx** [comment]
Can we make it possible to remix a single page within a project? The goal: lower the bar for participation and increase activity on the platform.

**Comment by cadecairos** [comment]
> Can we make it possible to remix a single page within a project? The goal: lower the bar for participation and increase activity on the platform.

see #7

**Comment by cadecairos** [comment]
Also,

* List Projects
  * GET /projects
    *  query parameters for sorting, pagination, optional flag to also retrieve page data for projects?

**Comment by xmatthewx** [comment]
> see #7

:boom:

**Comment by thisandagain** [comment]
I suggest we make `/projects` a sub-resource of `/users/:user` as it makes cache invalidation quite a bit easier and also properly reflects the ownership of the resource ala: `/users/:user/projects`.

**Comment by thisandagain** [comment]
I don't see anything in the designs that require sorting or retrieval of page data that would prohibit another HTTP request. Pagination seems like a requirement anywhere where the API is returning an array.

**Comment by davidascher** [comment]
We need localized searches, no? "Show recent/featured projects for this
locale?" "show recent/featured projects near this latlong?"

**Comment by thisandagain** [comment]
We don't have any features / UX for geolocation yet, just locale at this point.

**Comment by cadecairos** [comment]
@thisandagain we could have `/users/:user/projects` and also have `/projects` which defaults to listing either the authenticated user's projects, or the default list of public project data.

**Comment by thisandagain** [comment]
@cadecairos That's true ... I like the idea of having `/projects` be a raw feed of all project data. Having `/projects` list only the authenticated user's projects seems awfully non-restful and difficult to cache.

**Comment by thisandagain** [comment]
Here is a crack at another strawman:

#### API
```bash
GET /projects – List of all projects (both featured and not featured)
GET /users/:user/projects – List of all projects from the specified user
POST /users/:user/projects – Create a new project
GET /users/:user/projects/:project – Get an existing project by ID
PUT /users/:user/projects/:project – Update an existing project by ID (auth, owner)
DEL /users/:user/projects/:project – Delete an existing project by ID (auth, owner)
```

#### Data Model
```js
{
    "id": 1,
    "title": "Yam Fries 4000",
    "featured": true,
    "author": {
        "url": "billmurray",
        "username": "Bill Murray",
        "locale": "en_US",
        "permissions": {
            "staff": false,
            "moderator": false
        },
        "avatar": {
            // @todo
        }
    },
    "cover": {
        // @todo
    }
}
```

**Comment by cadecairos** [comment]
> POST /users/:user/projects/:project/remixes – Create a new remix of an existing project by ID ^ this last resource seems weird / wrong

the basis for that was https://developer.github.com/v3/repos/forks/#create-a-fork

**Comment by thisandagain** [comment]
Cool. Works for me! Thanks for the reference.
