### ISSUE TITLE
Set up thumbnail service

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/api.webmaker.org#64]
Set up service to generate a project's PNG thumbnail. For now, let's render the Page with the lowest ID (the initial page might be deleted).

**Comment by xmatthewx** [comment]
@toolness - any lessons learned from setting up your service? https://github.com/mozilla/webmaker-screenshot

**Comment by cadecairos** [comment]
is there any way we could do this using [AWS lambda](http://docs.aws.amazon.com/lambda/latest/dg/welcome.html)?

**Comment by xmatthewx** [comment]
Page will need to be cropped. Might be nice if this could be specified in the api call. Here's an approximation:  

![thumbnail crop](https://cloud.githubusercontent.com/assets/53411/7842722/f1efe3fa-0472-11e5-80a7-5e1d6c6fe38c.png)

**Comment by xmatthewx** [comment]
How about a quick async huddle to get off on the right foot? cc: @cadecairos @thisandagain @jbuck @simonwex @Pomax

**Comment by simonwex** [comment]
Async or sync? It'd be good to include @toolness, as he worked on a previous thumbnail service.

**Comment by cadecairos** [comment]
I'm not sure how useful [blitline](http://www.blitline.com/) will be here, unless we send it a URL that generates the project page we want screenshotted..

**Comment by cadecairos** [comment]
If we can publish a static version of [this](https://github.com/mozilla/webmaker-android/blob/1a2ef0bc55ad8feae76d6122f793db52274ca551/www_src/pages/page/page.jsx) somewhere, and control what data it renders (i.e. http://example.com/renderPage?pageId=45) we can then have <service TBD> screenshot it, and hand it off to <processing pipeline>

**Comment by simonwex** [comment]
* api.webmaker.org will provide a URL where the thumbnail is available (proxied by CloudFront)
  * This URL will contain the projectid + hash of the lowest-index page (the page that is the first loaded, likely, but not always [0,0]
 * Screenshot service will need to be modified to understand Webmaker projects
  * @toolness will create a ticket to describe this work
* Endpoint is required to render project home page for capture 
* Thumbnails will be updated 


* [ ] @toolness to create ticket on screenshot service for adding webmaker project (issue #: )
* [ ] @toolness to create ticket in MozillaFoundation/mofo-devops to cloudfront the S3 assets for screenshot service (issue #: )
* [ ] @cadecairos to create sequence diagram for screenshooting (?) the "home" page in Webmaker project
 * [x] @thisandagain to create ticket for rendering endpoint #71 
 * [ ] @simonwex to check on the deployment of screenshot service
 * [ ] @cadecairos to add hook for pre-generating updated thumbnails (issue #: )

**Comment by xmatthewx** [comment]
Thumbnail crop should be relative to the "page" rather than the page view that includes margins. As built, our thumbnails are a few pixels away from nice round proportions. Adjusted here for simplicity:

![thumbnail spec](https://cloud.githubusercontent.com/assets/53411/7892496/e8f36fcc-0622-11e5-9035-6189de003be9.png)

**Comment by toolness** [comment]
Is this cropping something we'll have to do in [webmaker-screenshot](https://github.com/mozilla/webmaker-screenshot) as part of the image processing pipeline we give to Blitline, or will it happen somewhere else? Sorry if this is a silly question, I'm new to this and still lacking some context...

**Comment by thisandagain** [comment]
This should happen as part of the image processing pipeline we give to Bitline:
Screenshot > Resize (max width) > Crop

Make sense @toolness ?

**Comment by toolness** [comment]
Ah got it, thanks Andrew.

Will Webmaker makes be the only use for webmaker-screenshot going forward? If so, I can just change the current hard-coded blitline pipeline to work in this new way; otherwise, I'll have to architect something that allows Webmaker makes to be cropped, while e.g. Thimble and Goggles makes remain uncropped, or something. Not a huge deal but given the tight deadline for this, I figured I'd bring it up!

**Comment by thisandagain** [comment]
I think so as we never got it hooked-up to the MakeAPI in production. We might want to check the logs to make 100% sure, but I think switching it over to this dedicated use-case makes sense from my POV. Thanks!

**Comment by cadecairos** [comment]
Just had a sync-up with @thisandagain @xmatthewx @toolness and @simonwex 

To summarize:
@toolness will:
1. add a new "viewport" to webmaker-screenshot that crops to the size we desire for screenshots.
2. Add a way to get the response from the server to return the screenshot url rather than a 302 to the screenshot (ideally using an ACCEPT header)
3. add a configuration option of some sort to find/replace the S3 host of screenshot URLs with the cloudfront prefix we configure for our screenshot bucket

@thisandagain will continue putting together an endpoint that can render an project and its elements as HTML, which will end up as the param we send to the screenshot service when we want to trigger a screenshot update.

I'm going to continue putting together the hooks in the Webmaker API that will trigger screenshot updates, when necessary. 

I'm sketching a diagram on my whiteboard to describe the flow, will update with a picture shortly,

**Comment by cadecairos** [comment]
![imag0492](https://cloud.githubusercontent.com/assets/438003/7923552/175eadf2-0882-11e5-9c97-efa1962e08ec.jpg)

**Comment by toolness** [comment]
Thanks @cadecairos, this is really helpful!!!

**Comment by simonwex** [comment]
Thanks for the update and diagram, @cadecairos.

**Comment by toolness** [comment]
**Update:** I'm working on adding support for this on the webmaker-screenshot end, but it seems like Blitline's PhantomJS renderer doesn't like Andrew's staging project: https://github.com/mozilla/webmaker-desktop/pull/76#issuecomment-108389541

**Comment by toolness** [comment]
> Add a way to get the response from the server to return the screenshot url rather than a 302 to the screenshot (ideally using an ACCEPT header)

I just added this in https://github.com/mozilla/webmaker-screenshot/commit/3c546da9f80e5b330b5d065296cccfd7b30dc956. /cc @cadecairos

> Add a configuration option of some sort to find/replace the S3 host of screenshot URLs with the cloudfront prefix we configure for our screenshot bucket

So I just realized that one of the features the screenshot service already supports is an optional [`S3_WEBSITE` environment variable](https://github.com/mozilla/webmaker-screenshot#optional-environment-variables):

> If your S3 bucket is hosted at a custom domain, you can optionally set `S3_WEBSITE` to its origin followed by a `/`, e.g. `http://my-webmaker-screenshots.com/`.

This was originally intended to work with S3's virtual hosting capabilities, but based on the little I know of how CloudFront works, I *think* it would work with CloudFront too. (Really `S3_WEBSITE` is just what's prepended to the S3 key name to provide the absolute URL to the resource.)  Any idea, @simonwex?

**Comment by cadecairos** [comment]
I'm continuing work on the tests for the API part of this. I will finish it off and get it merged tomorrow.

I need to know the final API that I'll be using with webmaker-screenshot (cc/ @toolness)

**Comment by thisandagain** [comment]
Thumbnail service is now landed and on staging for final testing:
https://webmaker-desktop-staging.herokuapp.com/#/thumbnail?user=1&project=1&page=1

**Comment by toolness** [comment]
NICE, the screenshotting service is rendering them properly:

![ahr0chm6ly93zwjtywtlci1kzxnrdg9wlxn0ywdpbmcuagvyb2t1yxbwlmnvbs8jl3rodw1ibmfpbd91c2vyptemchjvamvjdd0xjnbhz2u9mq](https://cloud.githubusercontent.com/assets/124687/7990722/f5d5d250-0ac0-11e5-9cdb-4bd4e5968402.jpg)

Now just need to properly [crop](https://github.com/mozilla/api.webmaker.org/issues/64#issuecomment-106934401) them.

What should the dimensions of the viewport be (i.e. the width/height we tell phantomJS to set the browser to)? 

And how much do we want to scale that after we've taken the screenshot?

**Comment by thisandagain** [comment]
Browser dimensions:
width: 320px
height: 440px

**Comment by toolness** [comment]
Ok cool, I just added the cropping in https://github.com/mozilla/webmaker-screenshot/commit/ff34605a5fa4ba94eac9fea1b485bdaa7c3f1288. I'm calling the viewport slug `mobile-center-cropped` but I'm open to better suggestions. Here's what it looks like on the [screenshot app](http://webmaker-screenshot.herokuapp.com/#https%3A%2F%2Fwebmaker-desktop-staging.herokuapp.com%2F%23%2Fthumbnail%3Fuser%3D1%26project%3D1%26page%3D1):

![2015-06-05_6-51-52](https://cloud.githubusercontent.com/assets/124687/8004657/89d6737c-0b4f-11e5-8471-e73027d8a7f8.jpg)

The crop dimensions are based on @xmatthewx's [specifications above](https://github.com/mozilla/api.webmaker.org/issues/64#issuecomment-106934401). I *think* I got the math right, but would appreciate a second opinion.

@cadecairos, if we stick with the viewport slug name, this means that you will want to use the [`GET /:viewport/:thumbnail/:key`](https://github.com/mozilla/webmaker-screenshot#get-viewportthumbnailkey) endpoint with the following parameters:

* `:viewport` set to `mobile-center-cropped`,
* `:thumbnail` set to `small`, and
* `:key` set to `webmaker-desktop/` followed by the URL to screenshot encoded as base64 (as per the [URL Parameters documentation](https://github.com/mozilla/webmaker-screenshot#url-parameters)).

Let me know if you have any questions!

**Comment by cadecairos** [comment]
@toolness Wonderful!

Does the GET route force a thumbnail to be generated? I thought POST did that

**Comment by toolness** [comment]
GET will create the thumbnail *if* it didn't already exist--if it does already exist, it returns it. POST is used to regenerate thumbnails if the original URL changed (remember, this was originally created for e.g. thimble makes where the project could be updated while still being at the same URL). IIRC from our meeting, @thisandagain said that for webmaker desktop, every version of every project will have its own unique URL, obviating the need for the POST endpoint. (Let me know if I mis-heard that though!)

**Comment by xmatthewx** [comment]
@secretrobotron - Can you give us the project ID for a project with good content? So we can test this better? Page with lowest ID will be rendered.

**Comment by cadecairos** [comment]
Here's a somewhat decent example

given this page: https://webmaker-desktop-staging.herokuapp.com/#/thumbnail?user=1&project=302&page=796

![](http://imgur.com/TEHkWd9l.png)

The service creates: http://webmaker-screenshot.herokuapp.com/mobile-center-cropped/small/webmaker-desktop/aHR0cHM6Ly93ZWJtYWtlci1kZXNrdG9wLXN0YWdpbmcuaGVyb2t1YXBwLmNvbS8jL3RodW1ibmFpbD91c2VyPTEmcHJvamVjdD0zMDImcGFnZT03OTY= 

![](https://s3.amazonaws.com/webmaker-screenshots.toolness.org/mobile-center-cropped/small/webmaker-desktop/aHR0cHM6Ly93ZWJtYWtlci1kZXNrdG9wLXN0YWdpbmcuaGVyb2t1YXBwLmNvbS8jL3RodW1ibmFpbD91c2VyPTEmcHJvamVjdD0zMDImcGFnZT03OTY=)

**Comment by xmatthewx** [comment]
:+1: I'd call that a success as far as rendering and cropping. We will need to test and see if users learn to optimize their page.

**Comment by secretrobotron** [comment]
Yeah, that looks nice. @xmatthewx need something from me still?
