### ISSUE TITLE
Design Pages API

### ISSUE THREAD

**Issue by cadecairos** [mozilla/api.webmaker.org#7]
* Create a page
  * POST /projects/:ProjectId/pages
* Update page data
  * PATCH /projects/:ProjectId/pages/:PageId
* Get data for a page
  * GET /projects/:ProjectId/pages/:PageId
* Delete a page
  * DELETE /projects/:ProjectId/page/:PageId
* Remix a page to another project
  * POST /projects/:ProjectId/page/:PageId/remixes
    * projectId json payload indicates destination project

**Comment by thisandagain** [comment]
I suggest we ditch "Remix a page to another project" as a requirement until we have a design that supports it. cc @xmatthewx

**Comment by xmatthewx** [comment]
We have [remix Page](https://docs.google.com/presentation/d/1ihVXe53q6U7YLKiYURKXedE5TzOW7x7iwCNeJBY4dpE/edit#slide=id.g99832357e_3_7) as a new project. We don't have import page to an existing project, and I'm not sure that we should b/c of the UI it would require.  

I'm fine with pushing this back in the roadmap if it's complicated. I do think it lowers the bar for participation and could be helpful for building momentum in the early days.

**Comment by thisandagain** [comment]
Gotcha. I'd like to punt as it muddies the metaphor quite a bit... let's keep it isolated to the project-level for now.

**Comment by xmatthewx** [comment]
Do you think we need to push this back beyond v1? :+1: Or, do you think it doesn't fit the platform?

**Comment by thisandagain** [comment]
Not needed for 1.0. Move to backlog.

**Comment by xmatthewx** [comment]
Cool. Moving to the backlog.

The web would be much less nimble if we could only point to and share sites, not pages. Our platform is more webby and more viable if we enable sharing and remixing of pages.

**Comment by thisandagain** [comment]
:+1: great point. Let's make sure to re-evaluate during the desktop design process.

**Comment by thisandagain** [comment]
#### API
```bash
POST /users/:user/projects/:project/pages – Create a new page
GET /users/:user/projects/:project/pages/:page – Get an existing page by ID
PUT /users/:user/projects/:project/pages/:page – Update an existing page by ID (auth, owner)
DEL /users/:user/projects/:project/pages/:page – Delete an existing page by ID (auth, owner)
```

#### Data Model
```js
{
    "id": 1,
    "x": 0,
    "y": 0,
    "history": {
        "created_at": "2015-04-20T16:11:13.961Z",
        "updated_at": "2015-04-20T16:11:13.961Z",
        "deleted_at": null,
    },
    "styles": {
        "background-color": "#ff0000"
    }
}
```

#### SQL
```sql
CREATE TABLE pages (
    id bigserial PRIMARY KEY,
    created_at timestamp DEFAULT current_timestamp,
    updated_at timestamp DEFAULT current_timestamp,
    deleted_at timestamp,
    x integer DEFAULT 0 NOT NULL,
    y integer DEFAULT 0 NOT NULL,
    project_id bigint NOT NULL,
    styles json,
    UNIQUE(project_id, x, y)
);
```

**Comment by cadecairos** [comment]
Also needed:
```
GET /user/{users}/projects/{project}/pages - get all pages in a project
```
