### ISSUE TITLE
Update Element schema

### ISSUE THREAD

**Issue by gvn** [mozilla/api.webmaker.org#74]
Add the following to the Element schema to allow links to have destinations...

```
target: {
  pageId: STRING
  projectId: STRING
}
```

**Comment by gvn** [comment]
CC: @cadecairos @thisandagain

**Comment by gvn** [comment]
Related to: https://github.com/mozilla/webmaker-android/issues/1670

**Comment by cadecairos** [comment]
Why not put that in the attributes jsonb field?

**Comment by gvn** [comment]
Not seeing that. Are we talking about the same thing? This is what I'm seeing:

![screenshot 2015-06-01 12 16 57](https://cloud.githubusercontent.com/assets/206379/7921153/446af0e6-0858-11e5-85fd-0d2b3c1305d2.png)

**Comment by cadecairos** [comment]
Might be a bug in the app parsing the response objects from the API? 

https://github.com/mozilla/api.webmaker.org/blob/a34778b36716f77c2a5862669d3013d8ffde26e1/scripts/create-tables.sql#L53

**Comment by gvn** [comment]
I must be looking at a massaged blob. Just looked at the raw response.

Not sure if this should be considered an "attribute" since those look like traditional HTML attributes to me. That said, I'm not sure where else to put it...

Thoughts @thisandagain @k88hudson @Pomax ?

**Comment by cadecairos** [comment]
The way I understand it, the attributes col is there for element specific data that's not generic enough to warrant a column of it's own. I think target falls into that category, as other element types wouldn't use it.

**Comment by k88hudson** [comment]
Let's discuss during the meeting, but I would recommend using the attributes field for this instead of a schema change

**Comment by gvn** [comment]
Ok, will put on attributes and keep it flat, so...

`targetPageId` and `targetProjectId`
