### ISSUE TITLE
Trick react into reloading project cards by appending somthing unique to thumbnail urls

### ISSUE THREAD

**Issue by cadecairos** [mozilla/api.webmaker.org#77]
React isn't updating its card component when thumbnails update because webmaker-screenshot always returns the same url. I can try cache busting by appending something unique to the image url, or we can add somthing unique before base64-ing the page render url

What do you think, @thisandagain?

**Comment by davidascher** [comment]
If the URL is lying that it's stable it should be fixed. You don't want to
bust caches on a given URL you want to make sure each new screenshot yields
a distinct URL.

**Comment by cadecairos** [comment]
I can use Date.now to make the page render url unique before base64 encoding it for webmaker-screenshot. that should always yield a unique thumbnail URL

**Comment by thisandagain** [comment]
You could use `Date.now` or (I think we talked about this) generate an MD5 hash of the page metadata to generate a unique checksum.

**Comment by cadecairos** [comment]
This was dealt with in #78
