### ISSUE TITLE
Load Test and Performance

### ISSUE THREAD

**Issue by simonwex** [mozilla/api.webmaker.org#84]
We need to do some basic load testing and fix any early bottlenecks.

**Comment by simonwex** [comment]
@cadecairos could you write a script that I can use to run a test? If you make it look like a user test-script, as in just instructions for a human, I can write it as a load-script.

**Comment by jbuck** [comment]
This is the most expensive query according to Heroku... but I can't find it in our code: 

`SELECT "id","type","page_id","created_at","updated_at","deleted_at","attributes","styles" FROM "public"."elements" ORDER BY "page_id" ASC`

https://postgres.heroku.com/databases/webmaker-api-heroku-postgresql-olive?addon_action=view_expensive_queries#metrics

**Comment by cadecairos** [comment]
@jbuck that might be @secretrobotron poking around?

**Comment by secretrobotron** [comment]
I'm not running that query explicitly. PSequel might be running it on my behalf though. Let me adjust settings.

**Comment by cadecairos** [comment]
@simonwex what kind of things do we want in the test?

There's plenty of routes on API.wmo

**Comment by thisandagain** [comment]
One way I sometimes do this is to use something like [Charles Proxy](http://www.charlesproxy.com/) and point your phone at your laptop as a network proxy. Then, you can just use the app like a normal user (look at stuff, create a few projects, etc) and you'll have a list of API requests that you can dump into a load testing script. It's a bit of work, but gives a much more realistic sense of an individual user's API load than just a list of endpoints. Hope that helps!

**Comment by thisandagain** [comment]
@jbuck Can you post the results of the load test here? How many concurrent virtual users / requests can we handle?

**Comment by jbuck** [comment]
@cadecairos Came up with a test script we can use as a basis for load testing: https://irccloud.mozilla.com/pastebin/8sckFI5b/testsession.txt

**Comment by thisandagain** [comment]
Perfect. Nice work @cadecairos !

**Comment by simonwex** [comment]
That test script looks representative, it's definitely one we should roll with. @jbuck did you run this one on LoadImpact? 

@cadecairos if we don't have results yet, could you take this over as next week?

**Comment by jbuck** [comment]
@simonwex no, I didn't run it on loadimpact. I'll send @cadecairos the credentials for the mofo loadimpact account

**Comment by cadecairos** [comment]
I played around with loadimpact and ran several tests against the staging server.

We start seeing long response times (and dropped responses) at around 300 reqs/minute. That's averaged by heroku's metrics, and I suspect the tipping point is somewhere more like 10+ requests/second

heroku dyno metrics show we're not maxing out CPU or Memory, and impactload reports less than 6MB of data received by 1000 users with the test script, so I think the increase in response time is the database gitting pinged far too often. We probably need a cache layer for get requests, and a sound solution for invalidating them. I had a patch in progress for this, but it needs some work.

**Comment by cadecairos** [comment]
cc/ @jbuck @simonwex @thisandagain

**Comment by cadecairos** [comment]
also worth noting that we're also pining id.wmo and it's PG database for auth'd requests to API.wmo, which is definitely increasing our response times.

**Comment by jbuck** [comment]
@cadecairos did the work here. Follow-up bugs to look at potential performance wins?

**Comment by cadecairos** [comment]
Caching being handled in #37
