### ISSUE TITLE
Set up webmaker-screenshot to use Mofo Blitline, S3 and Cloudfront

### ISSUE THREAD

**Issue by cadecairos** [mozilla/api.webmaker.org#86]
Putting this here to track progress

* [x] set up mofo blitline - MozillaFoundation/mofo-devops#100
* [x] Give Blitline write access to a mofo S3 bucket
* [x] Set up a Cloudfront distribution for the S3 Bucket
* [x] Configure webmaker-screenshot with new application id for blitline, s3 bucket and s3_website (poorly named, but will be the cloudfront url)

**Comment by jbuck** [comment]
@cadecairos are stumped as to how to get permissions on the S3 bucket to work with blitline. Paging @toolness
