### ISSUE TITLE
Design User API

### ISSUE THREAD

**Issue by cadecairos** [mozilla/api.webmaker.org#9]
What data do we need to store for each user ?

Routes
* Create user
  * POST /user
* Get user data
  * GET /user
* Update user data
  * PATCH /user
* Delete a user
  * DELETE /user

**Comment by xmatthewx** [comment]
Users will be simple in v1. I'd guess: name, email, avatar, projects, locale, join date, though I'm surely missing something. In Q3 we will add social features: favorites, comments, groups. 

Need input from @thisandagain 

We've talked about using a project page for making profile avatars. Definitely not v1.

**Comment by thisandagain** [comment]
Quick strawman proposal to expand on @cadecairos 's note above. Projects and project listings should be another end-point (`/users/:user/projects/:project`) IMO.

#### API
```bash
POST /users – Create a new user
GET /users/:user – Get an existing user by username
PUT /users/:user – Update user (requires authentication / ownership)
DEL /users/:user – Delete user (requires authentication / ownership)
```

#### User
```json
{
    "id": 1234,
    "url": "billmurray",
    "username": "Bill Murray",
    "locale": "en_US",
    "history": {
        "created_at": "2015-04-20T16:11:13.961Z",
        "updated_at": "2015-04-20T16:11:13.961Z",
        "deleted_at": null,
    },
    "permissions": {
        "staff": false,
        "moderator": false
    },
    "avatar": {
        // @todo
    }
}
```
