### ISSUE TITLE
Trying to update a page with the same coordinates as another returns obtuse error

### ISSUE THREAD

**Issue by k88hudson** [mozilla/api.webmaker.org#90]
When sending the following request
```
PATCH /users/1/projects/657/pages/1979
{ "y": "12"}
```

Where another page in that proejct has the same coordinates, the response is:

```
{
"statusCode": 500,
"error": "Internal Server Error",
"message": "An internal server error occurred"
}
```

It should be a more descriptive error.

Since this is basically impossible to hit except for a race condition in the app, this is low priority.

**Comment by cadecairos** [comment]
interesting, there should be unit tests for that

**Comment by cadecairos** [comment]
Turns out that pg and pg.native return different error formats! (yaaaaay)

If we want both of them to be an option, we'll just have to check for pg errors in both formats.

**Comment by cadecairos** [comment]
This is also causing 500s instead of 400s where we handle pg errors in the user handler.
